### ISSUE TITLE
An Exception: Unspecified error

### ISSUE THREAD

**Issue by mrsWolowitz** [elvirbrk/NoteHighlight2016#34]
`	using (PXRecord rec = 
			PXBase.SelectSingle<APSetup>(
					new PXField("Param")))
						{
							Param = false;
}`

When I select that code to convert I get the error:

![an exception unspecified error](https://user-images.githubusercontent.com/6136847/34718064-5d51253e-f546-11e7-9278-8df33925bb5d.png)

**Comment by elvirbrk** [comment]
I will look into it.

**Comment by ryleeferguson** [comment]
I'm receiving the same error, but not the same way.
I just highlighted 1 line in OneNote and attempted to set to PHP, then received the error
![image](https://user-images.githubusercontent.com/11593108/35023049-b0fdec8c-fb84-11e7-9dc2-26bcf316adc4.png)

**Comment by ryleeferguson** [comment]
Did some further troubleshooting and this issue seems to occur only when using **Shift+Enter** to continue on to the next line rather than just **Enter**.
E.g.
$foo = 'bar';(Shift+Enter)
content not to be highlighted

Will throw an error when attempting to highlight, doesn't change whether there is content on the next line or not. Seems to be the **Shift+Enter** character that's causing the issues in my case. (maybe it's only return \r instead of \r\n)

**Comment by elvirbrk** [comment]
@ryleeferguson Thanks for detailed analysis, that's probably why I couldn't reproduce issue with sample provided by @mrsWolowitz because those special characters were lost during process.

**Comment by elvirbrk** [comment]
Should be fixed in v3.3.
It was not an issue with Shift+Enter character, problem was that in OneNote words separated with Shift+Enter are still considered as part of same sentence, and this plugin didn't support formating only part of sentence, only whole lines.
In v3.3 it is supported to format only couple of words from line, so it should also fix this issue.

**Comment by grizz-pl** [comment]
same error occurs when there is a TAB used during writing code (not when it is pasted).

**Comment by ackimwilliams** [comment]
I'm running 3.4 and this error still shows up 

![image](https://user-images.githubusercontent.com/4093815/35478807-1d70e06c-03b5-11e8-9aec-e8f0b0fd2f90.png)

**Comment by elvirbrk** [comment]
Please provide sample text or sample OneNote page that is triggering this issue, because I cannot find a way to reproduce it.

**Comment by ackimwilliams** [comment]
The issue is with the \t tab character. When I switch to spaces it works fine. You probably need to do the same in a decorator.

**Comment by elvirbrk** [comment]
Still didn't manage to reproduce, no matter where I enter TAB or \t everything works fine.
Please describe step by step what I need to do to get this error.

**Comment by ContemplativeCoffeeCup** [comment]
![notehighlighterror](https://user-images.githubusercontent.com/33795450/40157935-895bab3a-5956-11e8-91d6-cce201b783c3.PNG)
Same issue. I was able to fix it by changing the code that I would highlight to being tabless, then adding my indentation within the dialogue.

**Comment by elvirbrk** [comment]
If you can provide sample page that is causing this error, that would be great.
I was trying to fix this, but I just coudn't reproduce this issue myself.

**Comment by SinZ163** [comment]
[Lab 5.zip](https://github.com/elvirbrk/NoteHighlight2016/files/3041155/Lab.5.zip)
A reproduction of it

**Comment by elvirbrk** [comment]
Should be fixed in v3.6
